-- Seed the current Dr. M Experienced public content catalog.

insert into public.content_topics (slug, label) values
  ('brain-fog', 'brain-fog'),
  ('brain-health', 'brain-health'),
  ('functional-medicine', 'functional-medicine'),
  ('sleep', 'sleep'),
  ('insomnia', 'insomnia'),
  ('emf', 'emf'),
  ('mood', 'mood'),
  ('detox', 'detox'),
  ('drainage', 'drainage'),
  ('chronic-infection', 'chronic-infection'),
  ('energy', 'energy'),
  ('mitochondria', 'mitochondria'),
  ('fatigue', 'fatigue'),
  ('mitochondrial-health', 'mitochondrial-health'),
  ('concussion', 'concussion'),
  ('traumatic-brain-injury', 'traumatic-brain-injury'),
  ('neuroinflammation', 'neuroinflammation'),
  ('blood-brain-barrier', 'blood-brain-barrier'),
  ('brain-autoimmunity', 'brain-autoimmunity'),
  ('blood-health', 'blood-health'),
  ('red-cell-function', 'red-cell-function'),
  ('circulation', 'circulation'),
  ('nutrition', 'nutrition'),
  ('food-as-medicine', 'food-as-medicine'),
  ('microglia', 'microglia'),
  ('blood-sugar', 'blood-sugar'),
  ('gut-brain-axis', 'gut-brain-axis'),
  ('nrf2', 'nrf2')
on conflict (slug) do update set label = excluded.label;

insert into public.episodes (
  slug,
  episode_number,
  title,
  publish_date,
  duration_minutes,
  summary,
  audio_url,
  vimeo_id,
  spotify_id,
  youtube_id,
  thumbnail_url
) values
  (
    'brain-fog-part-1',
    1,
    $$Brain Fog, Part 1 - Is Your Brain in a Fog?$$,
    '2026-01-20',
    17,
    $$Dr. David Musnick (Dr. M), board-certified in Internal Medicine and Sports Medicine with 35+ years in regenerative and functional medicine, dives straight into one of the most common complaints he sees: brain fog.$$,
    'https://content.rss.com/episodes/397420/3050766/dr-m-experienced/2026_08_07_05_37_14_57d1a0c9-5f80-4880-bc5d-57f7eeef7cb5.mp3',
    '1156414707',
    '7cAdb8GE4khC9EYKAjmYuc',
    '5IMYaqnQsFY',
    'https://drmexperienced.com/images/episodes/brain-fog-part-1.webp'
  ),
  (
    'brain-fog-part-2',
    2,
    $$Brain Fog, Part 2 - Testing and Basic Solutions$$,
    '2026-01-27',
    20,
    $$Dr. David Musnick (Dr. M) picks up where Part 1 left off and gets specific about which tests make sense for brain fog and which basics help almost everyone.$$,
    'https://content.rss.com/episodes/397420/3050765/dr-m-experienced/2026_08_07_05_41_20_c5dc584a-9799-404f-96e5-66fd2958ad94.mp3',
    '1159441883',
    '19Pct0ClX3j1EOwJ3ySVd7',
    'DJe0fPmTf8k',
    'https://drmexperienced.com/images/episodes/brain-fog-part-2.webp'
  ),
  (
    'episode-3-insomnia',
    3,
    $$Insomnia - Causes and Practical Sleep Strategies$$,
    '2026-04-03',
    20,
    $$Dr. M breaks down insomnia and sleep: difficulty falling or staying asleep, types of insomnia, and why 7+ hours of quality sleep matters for reducing inflammation in your brain and body—plus practical tools for wind-down, caffeine timing, natural supports, and more.$$,
    'https://content.rss.com/episodes/397420/3050764/dr-m-experienced/2026_08_07_05_42_30_c6bd9b48-095f-4ee9-9eda-ebb0d7956d09.mp3',
    '1179740758',
    '07OHz4sfbefOORcNi9xaUK',
    'r5JYtE8Vm9I',
    'https://drmexperienced.com/images/episodes/insomnia.webp'
  ),
  (
    'episode-4-emf',
    4,
    $$Electromagnetic Frequencies (EMF) - Practical Ways to Reduce Exposure$$,
    '2026-04-03',
    19,
    $$Dr. Musnick explains how RF, EMF, and electrical fields affect the brain and blood-brain barrier—and practical steps to reduce exposure from phones, WiFi, Bluetooth, vehicles, and smart meters.$$,
    'https://content.rss.com/episodes/397420/3050763/dr-m-experienced/2026_08_07_05_43_51_32e2ccc6-04c8-4592-9e50-aa8d48eb9cb8.mp3',
    '1179956166',
    '0aDVuIwrRlDKxEylMj2dyw',
    'binbLcb3f_s',
    'https://drmexperienced.com/images/episodes/emf.webp'
  ),
  (
    'episode-5-energy',
    5,
    $$Energy - Understanding Fatigue and Mitochondrial Health$$,
    '2026-06-26',
    30,
    $$Dr. M takes a functional-medicine look at energy, fatigue, and mitochondrial health, including sleep, inflammation, viral reactivation, infections, mold, heavy metals, hormones, organ stress, and practical supports for ATP production.$$,
    'https://content.rss.com/episodes/397420/3050762/dr-m-experienced/2026_08_22_21_31_50_62730fc1-465f-4df9-9c8a-d721be928586.mp3',
    '1204939658',
    '6fQAClcR4AAuueHjBNlrJC',
    'N_F0hhHkIQ4',
    'https://drmexperienced.com/images/episodes/energy-mitochondria.webp'
  ),
  (
    'episode-6-concussion-and-pathophysiology',
    6,
    $$Concussion - What Happens in the Brain$$,
    '2026-06-26',
    20,
    $$Dr. Musnick explains concussion and traumatic brain injury mechanisms, from neural shearing, excitotoxicity, neuroinflammation, oxidative stress, hypoxia, and blood-brain barrier disruption to persistent symptoms and recovery pathways.$$,
    'https://content.rss.com/episodes/397420/3050761/dr-m-experienced/2026_08_07_05_55_46_4806f336-163e-4ffb-b446-e4e03bb81013.mp3',
    '1204939692',
    '7MbKWgPZN40KEyN5j123JC',
    '8u1Ps_mCpO4',
    'https://drmexperienced.com/images/episodes/concussion-mechanics.webp'
  ),
  (
    'episode-7-the-brain-on-fire',
    7,
    $$The Brain on Fire - Neuroinflammation After Concussion$$,
    '2026-06-26',
    21,
    $$Dr. Musnick explains brain reserve and why symptom relief may precede full recovery, then explores glial cells, M1 and M2 microglia, neuroinflammation after concussion, and research-informed recovery factors.$$,
    'https://content.rss.com/episodes/397420/3050760/dr-m-experienced/2026_08_07_05_56_36_52e27ebd-6648-4ff7-adf3-f9f7731c1b86.mp3',
    '1205004739',
    '5QJlHSE6JhP3ymSCNzbWxv',
    '5UOEvs59hBA',
    'https://drmexperienced.com/images/episodes/brain-neuroinflammation.webp'
  ),
  (
    'episode-8-food-and-the-brain',
    8,
    $$Food and the Brain - Eating for Brain Health and Concussion Recovery$$,
    '2026-08-25',
    22,
    $$Dr. Musnick explains how he approaches eating for brain sharpness and concussion recovery, covering apigenin, choline, omega-3s, Nrf2-supportive foods, turmeric, quercetin, rosemary, protein, blood sugar, the microbiome, and selected elimination strategies.$$,
    'https://content.rss.com/episodes/397420/3096546/dr-m-experienced/2026_08_25_22_20_41_83110c46-278d-4dc5-96e7-d38abd74172a.mp3',
    '1221293570',
    '7oYwjErc5TXpocbRFgzvH0',
    'ax5BSELnBbo',
    'https://drmexperienced.com/images/episodes/food-and-the-brain.webp'
  )
on conflict (slug) do update set
  episode_number = excluded.episode_number,
  title = excluded.title,
  publish_date = excluded.publish_date,
  duration_minutes = excluded.duration_minutes,
  summary = excluded.summary,
  audio_url = excluded.audio_url,
  vimeo_id = excluded.vimeo_id,
  spotify_id = excluded.spotify_id,
  youtube_id = excluded.youtube_id,
  thumbnail_url = excluded.thumbnail_url,
  updated_at = now();

update public.episodes
   set status = 'published',
       updated_at = now()
 where slug = 'episode-8-food-and-the-brain'
   and status <> 'published';

insert into public.episode_topics (episode_slug, topic_slug) values
  ('brain-fog-part-1', 'brain-fog'),
  ('brain-fog-part-1', 'brain-health'),
  ('brain-fog-part-1', 'functional-medicine'),
  ('brain-fog-part-2', 'brain-fog'),
  ('brain-fog-part-2', 'brain-health'),
  ('brain-fog-part-2', 'functional-medicine'),
  ('episode-3-insomnia', 'sleep'),
  ('episode-3-insomnia', 'insomnia'),
  ('episode-3-insomnia', 'functional-medicine'),
  ('episode-4-emf', 'emf'),
  ('episode-4-emf', 'brain-health'),
  ('episode-4-emf', 'functional-medicine'),
  ('episode-5-energy', 'energy'),
  ('episode-5-energy', 'mitochondria'),
  ('episode-5-energy', 'fatigue'),
  ('episode-5-energy', 'mitochondrial-health'),
  ('episode-5-energy', 'functional-medicine'),
  ('episode-6-concussion-and-pathophysiology', 'concussion'),
  ('episode-6-concussion-and-pathophysiology', 'traumatic-brain-injury'),
  ('episode-6-concussion-and-pathophysiology', 'brain-health'),
  ('episode-6-concussion-and-pathophysiology', 'neuroinflammation'),
  ('episode-6-concussion-and-pathophysiology', 'functional-medicine'),
  ('episode-7-the-brain-on-fire', 'concussion'),
  ('episode-7-the-brain-on-fire', 'traumatic-brain-injury'),
  ('episode-7-the-brain-on-fire', 'brain-health'),
  ('episode-7-the-brain-on-fire', 'neuroinflammation'),
  ('episode-7-the-brain-on-fire', 'blood-brain-barrier'),
  ('episode-7-the-brain-on-fire', 'functional-medicine'),
  ('episode-8-food-and-the-brain', 'brain-health'),
  ('episode-8-food-and-the-brain', 'nutrition'),
  ('episode-8-food-and-the-brain', 'food-as-medicine'),
  ('episode-8-food-and-the-brain', 'concussion'),
  ('episode-8-food-and-the-brain', 'neuroinflammation'),
  ('episode-8-food-and-the-brain', 'functional-medicine'),
  ('episode-8-food-and-the-brain', 'microglia'),
  ('episode-8-food-and-the-brain', 'blood-sugar'),
  ('episode-8-food-and-the-brain', 'gut-brain-axis'),
  ('episode-8-food-and-the-brain', 'nrf2')
on conflict (episode_slug, topic_slug) do nothing;

insert into public.episode_references (episode_slug, label, url, display_order) values
  ('brain-fog-part-1', 'Watch on Vimeo', 'https://vimeo.com/1156414707', 10),
  ('brain-fog-part-1', 'Listen on Spotify', 'https://open.spotify.com/episode/7cAdb8GE4khC9EYKAjmYuc', 20),
  ('brain-fog-part-1', 'Watch on YouTube', 'https://www.youtube.com/watch?v=5IMYaqnQsFY', 30),
  ('brain-fog-part-1', 'Watch on Rumble', 'https://rumble.com/v74kzcw-episode-1-brain-fog-part-1-is-your-brain-in-a-fog.html', 40),
  ('brain-fog-part-2', 'Watch on Vimeo', 'https://vimeo.com/1159441883', 10),
  ('brain-fog-part-2', 'Listen on Spotify', 'https://open.spotify.com/episode/19Pct0ClX3j1EOwJ3ySVd7', 20),
  ('brain-fog-part-2', 'Watch on YouTube', 'https://www.youtube.com/watch?v=DJe0fPmTf8k', 30),
  ('brain-fog-part-2', 'Watch on Rumble', 'https://rumble.com/v74l0km-episode-brain-fog-part-2-testing-and-basic-solutions-for-brain-fog.html', 40),
  ('episode-3-insomnia', 'Watch on Vimeo', 'https://vimeo.com/1179740758', 10),
  ('episode-3-insomnia', 'Listen on Spotify', 'https://open.spotify.com/episode/07OHz4sfbefOORcNi9xaUK', 20),
  ('episode-3-insomnia', 'Watch on YouTube', 'https://www.youtube.com/watch?v=r5JYtE8Vm9I', 30),
  ('episode-3-insomnia', 'Watch on Rumble', 'https://rumble.com/v77zlls-episode-3-insomnia.html', 40),
  ('episode-4-emf', 'Watch on Vimeo', 'https://vimeo.com/1179956166', 10),
  ('episode-4-emf', 'Listen on Spotify', 'https://open.spotify.com/episode/0aDVuIwrRlDKxEylMj2dyw', 20),
  ('episode-4-emf', 'Watch on YouTube', 'https://www.youtube.com/watch?v=binbLcb3f_s', 30),
  ('episode-4-emf', 'Watch on Rumble', 'https://rumble.com/v780pxq-episode-4-emf.html', 40),
  ('episode-5-energy', 'Watch on Vimeo', 'https://vimeo.com/1204939658', 10),
  ('episode-5-energy', 'Listen on Spotify', 'https://open.spotify.com/episode/6fQAClcR4AAuueHjBNlrJC', 20),
  ('episode-5-energy', 'Watch on YouTube', 'https://www.youtube.com/watch?v=N_F0hhHkIQ4', 30),
  ('episode-5-energy', 'Watch on Rumble', 'https://rumble.com/v7bvj32-episode-5-electro.magnetic.frequencies.html', 40),
  ('episode-6-concussion-and-pathophysiology', 'Watch on Vimeo', 'https://vimeo.com/1204939692', 10),
  ('episode-6-concussion-and-pathophysiology', 'Listen on Spotify', 'https://open.spotify.com/episode/7MbKWgPZN40KEyN5j123JC', 20),
  ('episode-6-concussion-and-pathophysiology', 'Watch on YouTube', 'https://www.youtube.com/watch?v=8u1Ps_mCpO4', 30),
  ('episode-6-concussion-and-pathophysiology', 'Watch on Rumble', 'https://rumble.com/v7bvk8i-episode-6-concussion-and-pathophysiology.html', 40),
  ('episode-7-the-brain-on-fire', 'Watch on Vimeo', 'https://vimeo.com/1205004739', 10),
  ('episode-7-the-brain-on-fire', 'Listen on Spotify', 'https://open.spotify.com/episode/5QJlHSE6JhP3ymSCNzbWxv', 20),
  ('episode-7-the-brain-on-fire', 'Watch on YouTube', 'https://www.youtube.com/watch?v=5UOEvs59hBA', 30),
  ('episode-7-the-brain-on-fire', 'Watch on Rumble', 'https://rumble.com/v7bvtu4-episode-7-the-brain-on-fire.html', 40),
  ('episode-8-food-and-the-brain', 'Watch on Vimeo', 'https://vimeo.com/1221293570', 10),
  ('episode-8-food-and-the-brain', 'Listen on Spotify', 'https://open.spotify.com/episode/7oYwjErc5TXpocbRFgzvH0', 20),
  ('episode-8-food-and-the-brain', 'Watch on YouTube', 'https://youtu.be/ax5BSELnBbo', 30),
  ('episode-8-food-and-the-brain', 'Related: The Brain on Fire', 'https://drmexperienced.com/episodes/episode-7-the-brain-on-fire/', 100),
  ('episode-8-food-and-the-brain', 'Related: Concussion - What Happens in the Brain', 'https://drmexperienced.com/episodes/episode-6-concussion-and-pathophysiology/', 110),
  ('episode-8-food-and-the-brain', 'Affiliate and product guide', 'https://drmexperienced.com/affiliates/', 120),
  ('episode-8-food-and-the-brain', 'Dr. M Experienced Supplement Dispensary', 'https://drmexperienced.com/affiliates/#doctors-supplement-store', 130),
  ('episode-8-food-and-the-brain', 'Request the Healthy Brain Diet handout', 'https://drmexperienced.com/contact/', 140),
  ('episode-8-food-and-the-brain', 'HumanN Turmeric Chews', 'https://drmexperienced.com/affiliates/#humann-turmeric-chews', 150),
  ('episode-8-food-and-the-brain', 'FGO Turmeric Ginger Tea', 'https://drmexperienced.com/affiliates/#fgo-turmeric-ginger-tea', 160),
  ('episode-8-food-and-the-brain', 'Purity Coffee', 'https://drmexperienced.com/affiliates/#purity-coffee', 170),
  ('episode-8-food-and-the-brain', 'Purity laboratory information', 'https://puritycoffee.com/pages/independent-laboratory-tests', 180)
on conflict (episode_slug, url) do update set
  label = excluded.label,
  coming_soon = case
    when excluded.episode_slug = 'episode-8-food-and-the-brain' then false
    else episode_references.coming_soon
  end,
  display_order = excluded.display_order;

insert into public.episode_key_takeaways (episode_slug, display_order, body) values
  ($$brain-fog-part-1$$, 10, $$Brain fog is not normal at any age and indicates underlying dysfunction.$$),
  ($$brain-fog-part-1$$, 20, $$Core mechanisms include brain inflammation, dysfunctional microglia, and neurotransmitter issues.$$),
  ($$brain-fog-part-1$$, 30, $$Ignoring brain fog can lead to headaches, chronic fatigue, and cognitive decline.$$),
  ($$brain-fog-part-1$$, 40, $$Root causes range from excitotoxins (MSG & aspartame) to infections, heavy metals, and EMFs.$$),
  ($$brain-fog-part-1$$, 50, $$Functional testing to find root causes is essential rather than masking symptoms.$$),
  ($$brain-fog-part-2$$, 10, $$Brain fog reflects brain dysfunction with inflammation and slowed neurotransmission, not just being "tired" or "off."$$),
  ($$brain-fog-part-2$$, 20, $$Episodes of brain fog lasting more than 15–20 minutes, especially with memory, focus, or speech issues, need proper evaluation.$$),
  ($$brain-fog-part-2$$, 30, $$High-titer Epstein-Barr virus reactivation and mold/mycotoxins are common hidden drivers of persistent brain fog.$$),
  ($$brain-fog-part-2$$, 40, $$Standard EBV testing is often insufficient—full panels and correct cutoffs are required to see reactivation.$$),
  ($$brain-fog-part-2$$, 50, $$Foundational steps like sleep, exercise, EMF reduction, and toxin avoidance protect the brain while deeper root-cause work is underway.$$),
  ($$episode-3-insomnia$$, 10, $$Insomnia includes trouble falling asleep, staying asleep, or not getting enough hours—7+ hours of quality sleep helps reduce brain and body inflammation.$$),
  ($$episode-3-insomnia$$, 20, $$Aim to fall asleep in under 20 minutes; consistent bedtime (often 9–10 PM for adults) supports full 90-minute sleep cycles.$$),
  ($$episode-3-insomnia$$, 30, $$Blue-light blocking, wind-down routines, caffeine timing, and stress tools (mind dump, EFT tapping) can materially improve sleep.$$),
  ($$episode-3-insomnia$$, 40, $$Natural supports may include properly timed melatonin and homeopathy; antihistamines and alcohol often disrupt sleep architecture.$$),
  ($$episode-4-emf$$, 10, $$RF (phones, WiFi, Bluetooth, 5G), EMF from appliances/EVs, and electrical fields from wiring can affect the blood-brain barrier and contribute to brain fog, headaches, insomnia, and inflammation.$$),
  ($$episode-4-emf$$, 20, $$Mitigation starts with wired peripherals, airplane mode or distance from the phone at night, Ethernet + WiFi off overnight, and turning off Bluetooth/WiFi when idle.$$),
  ($$episode-4-emf$$, 30, $$Cars—especially EVs and hybrids—benefit from EMF testing before purchase; smart meters can be opted out or shielded.$$),
  ($$episode-4-emf$$, 40, $$Meters (e.g. Safe and Sound II, Tri-Field) help you measure home, car, and workplace; shielding, clothing, and pro assessments may help sensitive individuals.$$),
  ($$episode-5-energy$$, 10, $$Low energy is often more complex than being tired; sleep, sleep apnea, inflammation, infections, mold, heavy metals, hormones, and organ stress can all contribute.$$),
  ($$episode-5-energy$$, 20, $$Mitochondrial function and ATP production are central to daily vitality, resilience, and recovery.$$),
  ($$episode-5-energy$$, 30, $$Energy work starts with root-cause investigation instead of assuming a single supplement or stimulant will solve fatigue.$$),
  ($$episode-5-energy$$, 40, $$Foundational support can include grounding, better sleep, methylated B vitamins, magnesium, zinc, copper, CoQ10, NAD support, PQQ, and methylene blue when appropriate.$$),
  ($$episode-5-energy$$, 50, $$Supplement and testing decisions should be personalized with a clinician, especially when fatigue is persistent or complex.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 10, $$Concussion care should go beyond simply ruling out a brain bleed and telling someone to rest.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 20, $$Brain injury mechanisms can include structural injury, neural shearing, excitotoxicity, neuroinflammation, oxidative stress, hypoxia, and blood-brain barrier disruption.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 30, $$Persistent symptoms may involve brain autoimmunity, hormone and pituitary effects, vagus nerve dysfunction, mitochondrial dysfunction, protein folding abnormalities, and gut microbiome changes.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 40, $$Brain fog, headache, dizziness, emotional instability, fatigue, sleepiness, and brain-based fatigue can persist even when the person did not directly hit their head.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 50, $$The episode lays the mechanism foundation for future concussion recovery conversations and does not replace individualized medical evaluation.$$),
  ($$episode-7-the-brain-on-fire$$, 10, $$Brain reserve can differ across regions, so symptom improvement does not always mean the brain has fully restored its reserve.$$),
  ($$episode-7-the-brain-on-fire$$, 20, $$A healing brain needs protection from reinjury even after the most noticeable symptoms begin to improve.$$),
  ($$episode-7-the-brain-on-fire$$, 30, $$Astrocytes support the blood-brain barrier, oligodendrocytes help form myelin, and microglia respond to injury and inflammation.$$),
  ($$episode-7-the-brain-on-fire$$, 40, $$Prolonged pro-inflammatory M1 microglial activity can impair neurons and synapses, while repair-oriented M2 activity supports recovery.$$),
  ($$episode-7-the-brain-on-fire$$, 50, $$Sleep, selected foods and flavonoids, vitamin D, omega-3s, curcumin, and Nrf2 signaling are discussed as research-informed considerations, not a self-treatment protocol.$$),
  ($$episode-8-food-and-the-brain$$, 10, $$Dr. M organizes brain-focused nutrition around inflammatory balance, neuronal membrane support, steadier blood sugar, and a diverse gut microbiome.$$),
  ($$episode-8-food-and-the-brain$$, 20, $$Foods discussed include parsley and apigenin, wild blueberries, choline-rich eggs, lower-mercury seafood, broccoli sprouts, green tea, turmeric, quercetin-rich produce, and rosemary.$$),
  ($$episode-8-food-and-the-brain$$, 30, $$Protein quality, vegetable diversity, fiber, and food preparation are recurring practical themes throughout the episode.$$),
  ($$episode-8-food-and-the-brain$$, 40, $$The episode discusses limiting heavily browned foods, selected acrylamide and heavy-metal exposures, high-sugar foods, BPA and plastics, MSG, and aspartame.$$),
  ($$episode-8-food-and-the-brain$$, 50, $$Elimination diets, ketogenic eating, supplements, and fasting are presented as approaches to individualize with a qualified clinician rather than universal instructions.$$)
on conflict (episode_slug, display_order) do update set body = excluded.body;

insert into public.episode_checklist_items (episode_slug, display_order, body) values
  ($$brain-fog-part-1$$, 10, $$Eat organic, grass-fed, add parsley (for apigenin to calm microglia).$$),
  ($$brain-fog-part-1$$, 20, $$Prioritize 7.5+ hours of quality sleep.$$),
  ($$brain-fog-part-1$$, 30, $$Exercise daily to boost BDNF.$$),
  ($$brain-fog-part-1$$, 40, $$Reduce EMFs (WiFi off at night, phone away from head).$$),
  ($$brain-fog-part-1$$, 50, $$Avoid plastics and hidden toxins.$$),
  ($$episode-5-energy$$, 10, $$Start with sleep quality and screen for sleep apnea when fatigue persists.$$),
  ($$episode-5-energy$$, 20, $$Look for inflammatory, infectious, mold, heavy-metal, hormone, thyroid, adrenal, liver, kidney, and mitochondrial contributors.$$),
  ($$episode-5-energy$$, 30, $$Support ATP production with clinician-guided nutrition and supplement choices.$$),
  ($$episode-5-energy$$, 40, $$Use grounding, sleep improvement, and mitochondrial support as part of a broader root-cause plan.$$),
  ($$episode-8-food-and-the-brain$$, 10, $$Build a parsley and wild-blueberry smoothie with an individually appropriate protein source.$$),
  ($$episode-8-food-and-the-brain$$, 20, $$Include varied vegetables and fiber-rich foods to support microbiome diversity.$$),
  ($$episode-8-food-and-the-brain$$, 30, $$Review choline sources, protein quality, and lower-mercury seafood choices.$$),
  ($$episode-8-food-and-the-brain$$, 40, $$Pay attention to heavily browned or deep-fried foods, added sugar, large predatory fish, and plastic food packaging.$$),
  ($$episode-8-food-and-the-brain$$, 50, $$Discuss major elimination, ketogenic, fasting, or supplement changes with an appropriate clinician.$$)
on conflict (episode_slug, display_order) do update set body = excluded.body;

insert into public.episode_sections (episode_slug, display_order, title) values
  ($$brain-fog-part-1$$, 10, $$What is brain fog?$$),
  ($$brain-fog-part-1$$, 20, $$Core mechanisms$$),
  ($$brain-fog-part-1$$, 30, $$Potential causes$$),
  ($$brain-fog-part-1$$, 40, $$First steps to fight back$$),
  ($$brain-fog-part-2$$, 10, $$When brain fog is serious$$),
  ($$brain-fog-part-2$$, 20, $$Key testing for hidden drivers$$),
  ($$brain-fog-part-2$$, 30, $$Imaging and when to escalate$$),
  ($$brain-fog-part-2$$, 40, $$Universal basics while you test$$),
  ($$episode-3-insomnia$$, 10, $$What insomnia is$$),
  ($$episode-3-insomnia$$, 20, $$Sleep maintenance and routine$$),
  ($$episode-3-insomnia$$, 30, $$Light, stress, and natural supports$$),
  ($$episode-4-emf$$, 10, $$Types of electromagnetic exposure$$),
  ($$episode-4-emf$$, 20, $$Brain and barrier$$),
  ($$episode-4-emf$$, 30, $$What to do today$$),
  ($$episode-5-energy$$, 10, $$Why fatigue is usually multi-factorial$$),
  ($$episode-5-energy$$, 20, $$Mitochondria and ATP$$),
  ($$episode-5-energy$$, 30, $$Support tools discussed$$),
  ($$episode-6-concussion-and-pathophysiology$$, 10, $$Why concussion needs more than rest$$),
  ($$episode-6-concussion-and-pathophysiology$$, 20, $$What happens in the brain$$),
  ($$episode-6-concussion-and-pathophysiology$$, 30, $$Symptoms that can persist$$),
  ($$episode-6-concussion-and-pathophysiology$$, 40, $$Foundation for recovery discussions$$),
  ($$episode-7-the-brain-on-fire$$, 10, $$Brain reserve and symptom recovery$$),
  ($$episode-7-the-brain-on-fire$$, 20, $$Protecting a healing brain$$),
  ($$episode-7-the-brain-on-fire$$, 30, $$Glial cells and microglia$$),
  ($$episode-7-the-brain-on-fire$$, 40, $$Supporting inflammatory balance$$),
  ($$episode-8-food-and-the-brain$$, 10, $$Food, microglia, and neuronal membranes$$),
  ($$episode-8-food-and-the-brain$$, 20, $$Phytonutrients and practical recipes$$),
  ($$episode-8-food-and-the-brain$$, 30, $$Protein, blood sugar, and the microbiome$$),
  ($$episode-8-food-and-the-brain$$, 40, $$When stricter approaches need individual guidance$$)
on conflict (episode_slug, display_order) do update set title = excluded.title;

insert into public.episode_section_paragraphs (
  episode_slug,
  section_display_order,
  display_order,
  body
) values
  ($$brain-fog-part-1$$, 10, 10, $$Brain fog manifests as slow thinking, low mental energy, word-finding trouble, poor focus, and memory slips.$$),
  ($$brain-fog-part-1$$, 10, 20, $$It's not normal at any age and indicates underlying dysfunction that needs attention.$$),
  ($$brain-fog-part-1$$, 20, 10, $$Brain inflammation, dysfunctional microglia, and neurotransmitter issues are the primary mechanisms driving brain fog.$$),
  ($$brain-fog-part-1$$, 20, 20, $$Understanding these mechanisms helps guide targeted interventions rather than symptom masking.$$),
  ($$brain-fog-part-1$$, 30, 10, $$Dr. M outlines a comprehensive list: excitotoxins (MSG & aspartame), poor oxygen delivery, concussions, gluten/autoimmunity, blood sugar swings, hormones, mold, infections (EBV, Lyme, long COVID), heavy metals, EMFs, medications, and more.$$),
  ($$brain-fog-part-1$$, 30, 20, $$This wide range of causes underscores the importance of functional testing to identify root causes.$$),
  ($$brain-fog-part-1$$, 40, 10, $$Start with foundational interventions: eat organic, grass-fed foods, add parsley for apigenin to calm microglia.$$),
  ($$brain-fog-part-1$$, 40, 20, $$Prioritize 7.5+ hours of quality sleep, exercise daily to boost BDNF, reduce EMFs (WiFi off at night, phone away from head), and avoid plastics and hidden toxins.$$),
  ($$brain-fog-part-2$$, 10, 10, $$Brain fog is more serious when it comes with memory problems, poor focus, word-finding difficulty, or speech changes.$$),
  ($$brain-fog-part-2$$, 10, 20, $$Episodes that last longer than 15–20 minutes—especially when frequent—warrant careful evaluation rather than simple reassurance.$$),
  ($$brain-fog-part-2$$, 20, 10, $$Systemic inflammation markers and full Epstein-Barr virus panels (including VCA IgG/IgM, EBNA, and Early Antigen) can uncover reactivation that standard tests miss.$$),
  ($$brain-fog-part-2$$, 20, 20, $$Urine mycotoxin panels are appropriate when mold exposure is suspected, and homocysteine helps flag vascular stress on the brain.$$),
  ($$brain-fog-part-2$$, 30, 10, $$Brain MRI is not usually the first test for brain fog, but becomes important with progressive cognitive change or neurological red flags.$$),
  ($$brain-fog-part-2$$, 30, 20, $$Dr. M emphasizes matching the intensity of testing to symptom severity and pattern, not just ordering everything up front.$$),
  ($$brain-fog-part-2$$, 40, 10, $$While working up root causes, patients should still implement foundational brain-protective habits: 7.5+ hours of quality sleep, daily exercise to raise BDNF, and an organic/grass-fed diet.$$),
  ($$brain-fog-part-2$$, 40, 20, $$Other carry-overs from Part 1—parsley for apigenin, EMF reduction like turning WiFi off at night, and avoiding plastics/excitotoxins—remain essential.$$),
  ($$episode-3-insomnia$$, 10, 10, $$Dr. M defines insomnia as difficulty falling asleep, staying asleep, or getting insufficient sleep, and explains why adequate sleep duration matters for inflammation and recovery.$$),
  ($$episode-3-insomnia$$, 20, 10, $$Covers sleep-onset vs maintenance issues, teenagers’ delayed sleep phase, and building habits that help you fall back asleep when you wake at night.$$),
  ($$episode-3-insomnia$$, 30, 10, $$Discusses blue-light strategies, evening habits, morning light and daytime exercise, and cautious use of melatonin and homeopathic options—with product discount links in the show’s pinned comment where applicable.$$),
  ($$episode-4-emf$$, 10, 10, $$Dr. M outlines RF vs EMF vs electrical fields and where each shows up in daily life—from towers and earbuds to wiring and vehicles.$$),
  ($$episode-4-emf$$, 20, 10, $$How fields may stress the blood-brain barrier, symptoms that can follow, and why protecting sleep and barrier integrity matters for long-term brain health.$$),
  ($$episode-4-emf$$, 30, 10, $$Practical reduction strategies: hardwiring, nighttime WiFi habits, meter-based assessment, smart-meter choices, and resources referenced in pinned comments and show notes.$$),
  ($$episode-5-energy$$, 10, 10, $$Dr. M frames fatigue as a systems problem rather than a simple willpower or caffeine issue.$$),
  ($$episode-5-energy$$, 10, 20, $$Potential contributors include poor sleep, sleep apnea, inflammation, viral reactivation, Lyme and co-infections, mold exposure, heavy metals, hormone imbalance, adrenal and thyroid function, liver and kidney stress, and mitochondrial dysfunction.$$),
  ($$episode-5-energy$$, 20, 10, $$The episode connects daily energy to mitochondrial function and ATP production.$$),
  ($$episode-5-energy$$, 20, 20, $$Dr. M discusses why mitochondrial support can matter for vitality, resilience, and recovery, especially when fatigue has more than one driver.$$),
  ($$episode-5-energy$$, 30, 10, $$Practical support areas include grounding, improving sleep, methylated B vitamins, magnesium, zinc, copper, CoQ10, NAD support, PQQ, and methylene blue.$$),
  ($$episode-5-energy$$, 30, 20, $$These are presented as educational options to evaluate in a personalized medical context, not one-size-fits-all treatment instructions.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 10, 10, $$Dr. M explains why concussion evaluation should not stop at ruling out bleeding or major structural danger.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 10, 20, $$The episode focuses on the functional medicine mechanisms that can keep symptoms active after a head injury.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 20, 10, $$Mechanisms discussed include neural shearing, excitotoxicity, neuroinflammation, oxidative stress, hypoxia, blood-brain barrier disruption, brain autoimmunity, hormone dysfunction, pituitary involvement, vagus nerve dysfunction, mitochondrial dysfunction, protein folding abnormalities, neurogenesis, synaptogenesis, and gut microbiome changes.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 30, 10, $$Dr. M connects the mechanisms to symptoms such as brain fog, headache, dizziness, emotional instability, fatigue, sleepiness, and brain-based fatigue.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 30, 20, $$He also notes that concussion-like injury can occur even when someone does not directly hit their head.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 40, 10, $$This episode sets up later conversations on how to address concussion recovery pathways.$$),
  ($$episode-6-concussion-and-pathophysiology$$, 40, 20, $$Listeners are reminded to use personalized medical care for diagnosis, treatment, testing, supplements, and return-to-play decisions after head injury.$$),
  ($$episode-7-the-brain-on-fire$$, 10, 10, $$Dr. M explains that different brain regions can have different amounts of reserve before an injury becomes symptomatic.$$),
  ($$episode-7-the-brain-on-fire$$, 10, 20, $$Symptoms may improve once function rises above that threshold, even though the brain has not yet returned to its full pre-injury reserve.$$),
  ($$episode-7-the-brain-on-fire$$, 20, 10, $$The episode emphasizes protecting the brain from another impact while recovery is still underway.$$),
  ($$episode-7-the-brain-on-fire$$, 20, 20, $$Dr. M briefly revisits excitotoxicity from the preceding pathophysiology episode before focusing on neuroinflammation.$$),
  ($$episode-7-the-brain-on-fire$$, 30, 10, $$Astrocytes help support the blood-brain barrier, oligodendrocytes help form myelin, and microglia act as immune-support cells within the brain.$$),
  ($$episode-7-the-brain-on-fire$$, 30, 20, $$Dr. M contrasts prolonged pro-inflammatory M1 microglial activity, which can impair neurons and synapses, with repair-oriented M2 activity.$$),
  ($$episode-7-the-brain-on-fire$$, 40, 10, $$The discussion covers sleep, luteolin and apigenin, vitamin D, Nrf2 signaling, curcumin, and omega-3 fats as research-informed considerations.$$),
  ($$episode-7-the-brain-on-fire$$, 40, 20, $$These topics are educational and should be evaluated with an appropriate clinician rather than used as a stand-alone treatment or return-to-play protocol.$$),
  ($$episode-8-food-and-the-brain$$, 10, 10, $$Dr. M connects food choices with inflammatory M1 and repair-oriented M2 microglial activity, beginning with apigenin-rich parsley and a wild-blueberry smoothie.$$),
  ($$episode-8-food-and-the-brain$$, 10, 20, $$The discussion then turns to choline, omega-3 DHA, and other dietary building blocks involved in neuronal membranes.$$),
  ($$episode-8-food-and-the-brain$$, 20, 10, $$Broccoli sprouts, green tea, turmeric, quercetin-rich capers, red onions and apples, and rosemary appear in the episode's discussion of Nrf2 signaling and brain-focused eating.$$),
  ($$episode-8-food-and-the-brain$$, 20, 20, $$Dr. M shares practical ideas including a parsley smoothie and a cilantro-parsley pesto, and names HumanN Turmeric Chews and FGO Turmeric Ginger Tea as products listeners may want to research.$$),
  ($$episode-8-food-and-the-brain$$, 30, 10, $$The episode emphasizes protein quality, lower-mercury fish, vegetable diversity, fiber, steadier blood sugar, and a diverse gut microbiome.$$),
  ($$episode-8-food-and-the-brain$$, 30, 20, $$It also examines heavily browned foods, advanced glycation end products, acrylamide, plastics, MSG, aspartame, and the sourcing and testing questions Dr. M considers when discussing coffee.$$),
  ($$episode-8-food-and-the-brain$$, 40, 10, $$Dr. M explains why he may consider gluten-free, cow-dairy-free, low-lectin, ketogenic, fasting, or other selected elimination approaches in some neurological and concussion cases.$$),
  ($$episode-8-food-and-the-brain$$, 40, 20, $$These approaches are not universal. Major dietary changes, supplements, fasting, and elimination or ketogenic diets should be reviewed with a qualified healthcare professional.$$)
on conflict (episode_slug, section_display_order, display_order) do update set body = excluded.body;

insert into public.affiliate_categories (slug, label, description, display_order) values
  ('emf-rf-protection', 'EMF / RF Protection', $$Wearable, room, testing, and shielding tools connected to Dr. M's EMF and environmental-exposure conversations.$$, 10),
  ('sleep-light-environment', 'Sleep & Light Environment', $$Light-hygiene and circadian-support tools for sleep, insomnia, and evening routines.$$, 20),
  ('home-environment', 'Home Environment', $$Assessment and mitigation resources for home, bedroom, work, and travel environments.$$, 30),
  ('homeopathics-supplements', 'Homeopathics & Supplements', $$Homeopathic, drainage, detoxification, and supplement resources that need stronger clinical context.$$, 40),
  ('supplements', 'Supplements', $$Supplement dispensaries and product lines connected to functional-medicine and episode follow-up topics.$$, 50),
  ('food-and-nutrition', 'Food & Nutrition', $$Food and beverage resources connected to Dr. M's nutrition and brain-health discussions.$$, 60)
on conflict (slug) do update set
  label = excluded.label,
  description = excluded.description,
  display_order = excluded.display_order;

insert into public.affiliate_products (
  slug,
  category_slug,
  brand,
  name,
  summary,
  drm_thoughts,
  purchase_note,
  caution_note,
  affiliate_url,
  direct_url,
  coupon_code,
  discount_note,
  sort_order,
  date_added,
  last_reviewed,
  source_note
) values
  (
    'airestech',
    'emf-rf-protection',
    'Airestech',
    'EMF and RF Protection Devices',
    $$Wearable, phone, and room-focused EMF/RF protection devices for listeners who want a practical way to reduce exposure in daily environments.$$,
    $$Dr. M started using an Airestech Zone after years of EMF/RF-related headaches at his Bellevue clinic. After trying shielding paint and even a Swiss Shield canopy, he found the Zone helped enough that he now wears it daily and travels with it.$$,
    null,
    null,
    'https://airestech.com/davidmusnick',
    null,
    'DRDMUSNICK',
    'Use code DRDMUSNICK for at least 25% savings.',
    10,
    '2026-06-17',
    '2026-06-17',
    'David Musnick forwarded affiliate setup notes for Airestech.'
  ),
  (
    'block-blue-light',
    'sleep-light-environment',
    'BlockBlueLight',
    'Blue Light Blocking Glasses & Sleep Lighting',
    $$Blue-light blocking glasses, sleep-friendly reading lights, and home lighting products for reducing artificial light exposure in the evening.$$,
    $$Dr. M likes this as a practical sleep-hygiene tool: glasses and lighting that make it easier to wind down without flooding the eyes with bright blue light before bed.$$,
    null,
    null,
    'https://www.blockbluelight.com/?ref=drmexperienced',
    null,
    null,
    'Listener discount is applied through the affiliate link.',
    20,
    '2026-06-17',
    '2026-06-17',
    'Existing affiliate entry reviewed during affiliate catalog pass.'
  ),
  (
    'safe-living-technologies',
    'home-environment',
    'Safe Living Technologies',
    'EMF Testing & Shielding Tools',
    $$EMF meters, testing resources, and shielding products for people who want a more concrete look at their home or work environment.$$,
    $$Dr. M flagged Safe Living Technologies for EMF testing and shielding, especially for listeners who want to measure first and make practical changes based on what they find.$$,
    null,
    null,
    null,
    'https://safelivingtechnologies.com/',
    'DrMExperienced',
    null,
    30,
    '2026-06-17',
    '2026-06-17',
    'Existing EMF resource reviewed against current episode context.'
  ),
  (
    'desbio-dbscript',
    'homeopathics-supplements',
    'DesBio / DBscript',
    'Homeopathic and Drainage Product Access',
    $$A DBscript store for DesBio homeopathic and supplement products that Dr. M may reference for emotional support, drainage, detoxification, and functional-medicine conversations.$$,
    $$Dr. M describes DesBio as a leading source for homeopathic products used in areas such as anxiety, mood, motivation, drainage, detoxification, and chronic-infection protocols.$$,
    'Open the DBscript link, then search for the product name.',
    $$DesBio also makes products for chronic viral, bacterial, and tickborne-infection protocols. Dr. M does not recommend those generically; review them through a consult or your own clinician.$$,
    null,
    'https://dbscript.com/?direct=DrMEx',
    null,
    null,
    40,
    '2026-06-17',
    '2026-06-17',
    'David Musnick forwarded DBscript setup and product-list notes.'
  ),
  (
    'best365labs',
    'supplements',
    'Best365Labs',
    'Methylene Blue & Brain/Energy Supplements',
    $$A supplement source Dr. M noted for methylene blue and other brain and energy related products.$$,
    $$Dr. M pointed to Best365Labs in the context of brain and energy support. These products should be considered in a clinical context, especially for people with medications, complex conditions, or sensitivity to supplements.$$,
    null,
    null,
    null,
    'https://best365labs.com/',
    'DrME',
    null,
    50,
    '2026-06-17',
    '2026-06-17',
    'Existing supplement resource reviewed during affiliate catalog pass.'
  ),
  (
    'doctors-supplement-store',
    'supplements',
    'Doctors Supplement Store',
    $$Dr. M Experienced Supplement Dispensary$$,
    $$A DSS supplement dispensary for the Dr. M Experienced audience, with thousands of high-quality practitioner-focused supplement products.$$,
    $$Dr. M flagged DSS as a way to give podcast listeners one place to research and purchase high-quality supplements connected to future show notes, webinars, and protocol discussions while keeping podcast activity organized.$$,
    $$This is the Dr. M Experienced dispensary URL.$$,
    null,
    null,
    'https://dssorders.com/DrMExperienced',
    null,
    null,
    60,
    '2026-06-17',
    '2026-06-17',
    'David Musnick forwarded DSS dispensary URL and catalog notes.'
  ),
  (
    'abeytu-naturals',
    'supplements',
    'Abeytu Naturals',
    'Blood & Red Cell Support Supplements',
    $$A supplement company Dr. M highlighted for blood-health and red-cell function support.$$,
    $$Dr. M's note on Abeytu Naturals was centered on helping clean the blood and improve red-cell function. It may fit conversations about oxygen delivery and whole-body function, but listeners should review supplement choices with their own clinician.$$,
    null,
    null,
    'https://abeytunaturals.com/discount/DRDAVID10',
    'https://abeytunaturals.com/',
    'DRDAVID10',
    'Use code DRDAVID10 for 10% off.',
    70,
    '2026-06-17',
    '2026-06-17',
    'David Musnick forwarded Abeytu discount and blood-health notes.'
  ),
  (
    'humann-turmeric-chews',
    'supplements',
    'HumanN',
    'Turmeric Chews',
    $$The turmeric and curcumin chew Dr. M names in Episode 8 as one convenient way to include turmeric.$$,
    $$Dr. M mentions HumanN Turmeric Chews while discussing practical ways to include turmeric in a brain-focused food plan. This official product page is provided for listeners who want to research the exact item named in the episode.$$,
    $$Direct official product link; no Dr. M affiliate URL is currently recorded.$$,
    $$Supplement choices are not one-size-fits-all and should be reviewed with an appropriate clinician when relevant.$$,
    null,
    'https://humann.com/products/turmeric-chews',
    null,
    null,
    80,
    '2026-08-25',
    '2026-08-25',
    'Named by Dr. M in Episode 8; official HumanN product page verified 2026-08-25.'
  ),
  (
    'fgo-turmeric-ginger-tea',
    'food-and-nutrition',
    'FGO / From Great Origins',
    'Turmeric Ginger Tea',
    $$The turmeric, ginger, and cinnamon tea Dr. M names in Episode 8 as a food-and-beverage option for turmeric.$$,
    $$Dr. M mentions FGO Turmeric Ginger Tea as a practical alternative to using turmeric only as a spice or supplement. This official product page is provided for listeners who want to research the exact tea named in the episode.$$,
    $$Direct official product link; no Dr. M affiliate URL is currently recorded.$$,
    $$Food, beverage, and supplement choices should be individualized for allergies, medications, and other health considerations.$$,
    null,
    'https://fromgreatorigins.com/products/turmeric-ginger-tea-bags',
    null,
    null,
    90,
    '2026-08-25',
    '2026-08-25',
    'Named by Dr. M in Episode 8; official From Great Origins product page verified 2026-08-25.'
  ),
  (
    'purity-coffee',
    'food-and-nutrition',
    'Purity Coffee',
    'Organic Whole Bean Coffee',
    $$The organic whole-bean coffee brand Dr. M names in Episode 8 while discussing coffee, acrylamide, mold, and product testing.$$,
    $$Dr. M points listeners to Purity Coffee while explaining why he pays attention to how coffee is sourced and tested. The brand also publishes laboratory-testing information for listeners who want to review it.$$,
    $$Direct official product-category link; no Dr. M affiliate URL is currently recorded. Purity's laboratory information is linked in the Episode 8 show notes.$$,
    $$Coffee and caffeine tolerance vary; consider individual sleep, medication, pregnancy, and medical context.$$,
    null,
    'https://puritycoffee.com/collections/whole-bean-coffee',
    null,
    null,
    100,
    '2026-08-25',
    '2026-08-25',
    'Named by Dr. M in Episode 8; official Purity Coffee product and laboratory-information pages verified 2026-08-25.'
  )
on conflict (slug) do update set
  category_slug = excluded.category_slug,
  brand = excluded.brand,
  name = excluded.name,
  summary = excluded.summary,
  drm_thoughts = excluded.drm_thoughts,
  purchase_note = excluded.purchase_note,
  caution_note = excluded.caution_note,
  affiliate_url = excluded.affiliate_url,
  direct_url = excluded.direct_url,
  coupon_code = excluded.coupon_code,
  discount_note = excluded.discount_note,
  sort_order = excluded.sort_order,
  last_reviewed = excluded.last_reviewed,
  source_note = excluded.source_note,
  updated_at = now();

insert into public.affiliate_product_reasons (product_slug, display_order, body) values
  ('airestech', 10, $$Includes wearable options as well as room-level devices, so listeners can match the tool to the exposure setting.$$),
  ('airestech', 20, $$Relevant for people following Dr. M's EMF/RF discussions and wanting a product source to research.$$),
  ('airestech', 30, $$The current partner link and code are active through Airestech's partner program.$$),
  ('block-blue-light', 10, $$Useful for listeners working on insomnia, circadian rhythm, and evening screen or light exposure.$$),
  ('block-blue-light', 20, $$Includes both wearable glasses and room-level lighting options, so people can address more than one source of nighttime light.$$),
  ('block-blue-light', 30, $$The referral link applies the listener discount automatically.$$),
  ('safe-living-technologies', 10, $$Focused on assessment tools as well as shielding products.$$),
  ('safe-living-technologies', 20, $$Pairs well with a measured, room-by-room approach to reducing exposure instead of guessing.$$),
  ('safe-living-technologies', 30, $$Useful for listeners following the EMF episode and wanting product sources to research.$$),
  ('desbio-dbscript', 10, $$The direct DBscript link gives listeners one place to search for DesBio products Dr. M mentions.$$),
  ('desbio-dbscript', 20, $$The line includes broadly relevant emotional-support, drainage, detox, and brain-support formulas.$$),
  ('desbio-dbscript', 30, $$It can support future podcast follow-up without turning an episode page into a full treatment protocol.$$),
  ('best365labs', 10, $$Relevant to the brain fog and energy conversations already covered on the show.$$),
  ('best365labs', 20, $$Gives listeners one named source to research when methylene blue or mitochondrial-support topics come up.$$),
  ('best365labs', 30, $$Includes a public listener code for the Dr. M Experienced audience.$$),
  ('doctors-supplement-store', 10, $$Broad supplement catalog rather than a single-product line.$$),
  ('doctors-supplement-store', 20, $$Separate Dr. M Experienced dispensary URL keeps podcast-related supplement activity organized.$$),
  ('doctors-supplement-store', 30, $$Useful as a central destination when future episodes or webinars mention supplement categories.$$),
  ('abeytu-naturals', 10, $$Connects to the broader functional-medicine lens of oxygen delivery, circulation, and cellular function.$$),
  ('abeytu-naturals', 20, $$The public discount link gives listeners a straightforward way to find the line Dr. M referenced.$$),
  ('abeytu-naturals', 30, $$A useful category to discuss when red-cell function is part of a larger health plan.$$),
  ('humann-turmeric-chews', 10, $$Provides the exact branded turmeric chew named in Episode 8.$$),
  ('humann-turmeric-chews', 20, $$The direct link goes to HumanN's official product page.$$),
  ('humann-turmeric-chews', 30, $$A chew format gives listeners another option to compare with turmeric used as a spice or tea.$$),
  ('fgo-turmeric-ginger-tea', 10, $$Provides the exact branded turmeric tea named in Episode 8.$$),
  ('fgo-turmeric-ginger-tea', 20, $$The direct link goes to From Great Origins' official product page.$$),
  ('fgo-turmeric-ginger-tea', 30, $$A tea format gives listeners another way to compare turmeric options.$$),
  ('purity-coffee', 10, $$Provides the exact coffee brand named in Episode 8.$$),
  ('purity-coffee', 20, $$The direct link goes to Purity Coffee's official whole-bean collection.$$),
  ('purity-coffee', 30, $$Purity publishes a separate laboratory-information page for listeners evaluating its testing claims.$$)
on conflict (product_slug, display_order) do update set body = excluded.body;

insert into public.affiliate_product_use_cases (product_slug, display_order, body) values
  ('airestech', 10, $$Wearable EMF/RF exposure support$$),
  ('airestech', 20, $$Cell-phone exposure mitigation$$),
  ('airestech', 30, $$Bedroom and hotel-room protection$$),
  ('airestech', 40, $$Larger-room protection with the Zone Max$$),
  ('block-blue-light', 10, $$Evening screen use$$),
  ('block-blue-light', 20, $$Reading before bed$$),
  ('block-blue-light', 30, $$Sleep-supportive home lighting$$),
  ('block-blue-light', 40, $$Circadian rhythm and insomnia routines$$),
  ('safe-living-technologies', 10, $$Home EMF testing$$),
  ('safe-living-technologies', 20, $$Bedroom and workspace assessment$$),
  ('safe-living-technologies', 30, $$Shielding product research$$),
  ('safe-living-technologies', 40, $$Reducing avoidable environmental exposures$$),
  ('desbio-dbscript', 10, $$Emotional-support product research$$),
  ('desbio-dbscript', 20, $$Drainage and detoxification conversations$$),
  ('desbio-dbscript', 30, $$Brain and nervous-system support topics$$),
  ('desbio-dbscript', 40, $$Clinician-guided chronic-infection protocol discussions$$),
  ('best365labs', 10, $$Brain-support supplement research$$),
  ('best365labs', 20, $$Energy and mitochondrial support conversations$$),
  ('best365labs', 30, $$Brain fog protocol discussions with a clinician$$),
  ('best365labs', 40, $$Functional medicine supplement planning$$),
  ('doctors-supplement-store', 10, $$Practitioner-grade supplement research$$),
  ('doctors-supplement-store', 20, $$Podcast and webinar follow-up resources$$),
  ('doctors-supplement-store', 30, $$Brain, immune, orthopedic, and functional-medicine supplement categories$$),
  ('doctors-supplement-store', 40, $$Centralized supplement ordering for listeners$$),
  ('abeytu-naturals', 10, $$Blood-health supplement research$$),
  ('abeytu-naturals', 20, $$Red-cell function conversations$$),
  ('abeytu-naturals', 30, $$Oxygen-delivery and circulation support discussions$$),
  ('abeytu-naturals', 40, $$Clinician-guided supplement planning$$),
  ('humann-turmeric-chews', 10, $$Researching the turmeric chew mentioned in Episode 8$$),
  ('humann-turmeric-chews', 20, $$Comparing turmeric and curcumin formats$$),
  ('humann-turmeric-chews', 30, $$Following the episode's discussion of Nrf2-supportive foods$$),
  ('fgo-turmeric-ginger-tea', 10, $$Researching the turmeric tea mentioned in Episode 8$$),
  ('fgo-turmeric-ginger-tea', 20, $$Comparing food, beverage, and supplement forms of turmeric$$),
  ('fgo-turmeric-ginger-tea', 30, $$Following the episode's brain-health nutrition discussion$$),
  ('purity-coffee', 10, $$Researching the coffee brand mentioned in Episode 8$$),
  ('purity-coffee', 20, $$Comparing organic whole-bean coffee options$$),
  ('purity-coffee', 30, $$Reviewing a brand's published coffee-testing information$$)
on conflict (product_slug, display_order) do update set body = excluded.body;

insert into public.affiliate_product_featured_items (product_slug, display_order, label) values
  ('airestech', 10, 'Go'),
  ('airestech', 20, 'Flex'),
  ('airestech', 30, 'Zone'),
  ('airestech', 40, 'Zone Max'),
  ('desbio-dbscript', 10, 'Esteem'),
  ('desbio-dbscript', 20, 'Rage'),
  ('desbio-dbscript', 30, 'Anxious'),
  ('desbio-dbscript', 40, 'Motivation'),
  ('desbio-dbscript', 50, 'Grief'),
  ('desbio-dbscript', 60, 'Adrenal Support'),
  ('desbio-dbscript', 70, 'Allergy Rescue'),
  ('desbio-dbscript', 80, 'Appetite Control'),
  ('desbio-dbscript', 90, 'Celergesic'),
  ('desbio-dbscript', 100, 'Cerebromax'),
  ('desbio-dbscript', 110, 'Comprehensive Homeopathic Detox Kit'),
  ('desbio-dbscript', 120, 'Crave Control'),
  ('desbio-dbscript', 130, 'Dizzy'),
  ('desbio-dbscript', 140, 'Dynamic Brain'),
  ('desbio-dbscript', 150, 'Ear Ring'),
  ('desbio-dbscript', 160, 'Emotional Detox and Drainage'),
  ('desbio-dbscript', 170, 'GLP Support'),
  ('desbio-dbscript', 180, 'Headache'),
  ('desbio-dbscript', 190, 'HeadSSR'),
  ('desbio-dbscript', 200, 'Herx'),
  ('desbio-dbscript', 210, 'Leaky Gut Formula')
on conflict (product_slug, display_order) do update set label = excluded.label;

insert into public.affiliate_product_episode_links (product_slug, episode_slug, link_reason) values
  ('airestech', 'episode-4-emf', 'EMF/RF episode'),
  ('block-blue-light', 'episode-3-insomnia', 'sleep and light hygiene'),
  ('block-blue-light', 'episode-4-emf', 'EMF/light-environment crossover'),
  ('safe-living-technologies', 'episode-4-emf', 'EMF testing and shielding'),
  ('desbio-dbscript', 'brain-fog-part-1', 'brain fog and root-cause support'),
  ('desbio-dbscript', 'brain-fog-part-2', 'brain fog and root-cause support'),
  ('best365labs', 'brain-fog-part-1', 'brain and energy support'),
  ('best365labs', 'brain-fog-part-2', 'brain and energy support'),
  ('doctors-supplement-store', 'episode-8-food-and-the-brain', 'brain-health nutrition resources'),
  ('humann-turmeric-chews', 'episode-8-food-and-the-brain', 'turmeric product named in Episode 8'),
  ('fgo-turmeric-ginger-tea', 'episode-8-food-and-the-brain', 'turmeric tea named in Episode 8'),
  ('purity-coffee', 'episode-8-food-and-the-brain', 'coffee brand named in Episode 8')
on conflict (product_slug, episode_slug) do update set link_reason = excluded.link_reason;

insert into public.affiliate_product_auto_topics (product_slug, topic_slug) values
  ('airestech', 'emf'),
  ('block-blue-light', 'sleep'),
  ('block-blue-light', 'insomnia'),
  ('safe-living-technologies', 'emf'),
  ('desbio-dbscript', 'brain-fog'),
  ('desbio-dbscript', 'mood'),
  ('desbio-dbscript', 'detox'),
  ('desbio-dbscript', 'drainage'),
  ('desbio-dbscript', 'chronic-infection'),
  ('best365labs', 'brain-fog'),
  ('best365labs', 'energy'),
  ('best365labs', 'mitochondria'),
  ('abeytu-naturals', 'blood-health'),
  ('abeytu-naturals', 'red-cell-function'),
  ('abeytu-naturals', 'circulation'),
  ('humann-turmeric-chews', 'nrf2'),
  ('fgo-turmeric-ginger-tea', 'nrf2'),
  ('purity-coffee', 'nutrition')
on conflict (product_slug, topic_slug) do nothing;

insert into public.affiliate_product_tags (product_slug, tag_slug) values
  ('airestech', 'emf'),
  ('airestech', 'rf'),
  ('airestech', 'wearable'),
  ('airestech', 'room-protection'),
  ('airestech', 'travel'),
  ('block-blue-light', 'sleep'),
  ('block-blue-light', 'insomnia'),
  ('block-blue-light', 'circadian-rhythm'),
  ('block-blue-light', 'light-hygiene'),
  ('safe-living-technologies', 'emf'),
  ('safe-living-technologies', 'shielding'),
  ('safe-living-technologies', 'testing'),
  ('safe-living-technologies', 'home-environment'),
  ('desbio-dbscript', 'homeopathics'),
  ('desbio-dbscript', 'desbio'),
  ('desbio-dbscript', 'detox'),
  ('desbio-dbscript', 'drainage'),
  ('desbio-dbscript', 'brain-health'),
  ('best365labs', 'brain-health'),
  ('best365labs', 'energy'),
  ('best365labs', 'mitochondria'),
  ('best365labs', 'supplements'),
  ('doctors-supplement-store', 'supplements'),
  ('doctors-supplement-store', 'dispensary'),
  ('doctors-supplement-store', 'brain-health'),
  ('doctors-supplement-store', 'immune-support'),
  ('doctors-supplement-store', 'orthopedics'),
  ('abeytu-naturals', 'blood-health'),
  ('abeytu-naturals', 'red-cell-function'),
  ('abeytu-naturals', 'circulation'),
  ('abeytu-naturals', 'supplements'),
  ('humann-turmeric-chews', 'brain-health'),
  ('humann-turmeric-chews', 'nutrition'),
  ('humann-turmeric-chews', 'turmeric'),
  ('humann-turmeric-chews', 'curcumin'),
  ('humann-turmeric-chews', 'supplements'),
  ('fgo-turmeric-ginger-tea', 'brain-health'),
  ('fgo-turmeric-ginger-tea', 'nutrition'),
  ('fgo-turmeric-ginger-tea', 'turmeric'),
  ('fgo-turmeric-ginger-tea', 'ginger'),
  ('fgo-turmeric-ginger-tea', 'tea'),
  ('purity-coffee', 'brain-health'),
  ('purity-coffee', 'nutrition'),
  ('purity-coffee', 'coffee'),
  ('purity-coffee', 'organic'),
  ('purity-coffee', 'food-quality')
on conflict (product_slug, tag_slug) do nothing;
